
version: "3.6"

services:
  kingdombattles:
    container_name: kingdombattles
    restart: always
    build: .
    ports:
      - 80
    volumes:
      - static_volume:/app/public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kingdombattlesrouter.rule=Host(`kingdombattles.net`)"
      - "traefik.http.routers.kingdombattlesrouter.entrypoints=websecure"
      - "traefik.http.routers.kingdombattlesrouter.tls.certresolver=myresolver"
      - "traefik.http.routers.kingdombattlesrouter.service=kingdombattlesservice@docker"
      - "traefik.http.services.kingdombattlesservice.loadbalancer.server.port=3000"
    networks:
      - traefik-network

volumes:
  static_volume:
    driver: local

networks:
  traefik-network:
    external: true
